### PR TITLE
fix: workaround for git init fatal

### PR DESCRIPTION
**Pull request by arnikasky**
**Description**
> Provide a description of what your changes do.

**Testing Instructions**
> Give us step by step instructions on how to test your changes.

**Additional Notes**
> Anything else that will help us test the pull request.

### CODE REVIEW

**Comment by pagnkelly** [comment]
这个pr是解决 
```js
Initialized empty Git repository in /github/workspace/packages/.vuepress/dist/.git/
fatal: not in a git directory
```
这个问题的吗。我今天新创建的一个文档ci 明明git init了 却还是在git config xx报错

**Comment by pagnkelly** [comment]
seem like `git init` error,it 's not same to me

**Comment by arnikasky** [comment]
@pagnkelly but it fixed the problem

**Comment by pagnkelly** [comment]
@arnikasky yeah, it's awesome!

**Comment by ninoseki** [comment]
FYI I just confirmed that this workaround works.

**Comment by lmarzen** [comment]
This workaround still works. @jenkey2011, is there something blocking this PR?

**Comment by selankon** [comment]
This fixes https://github.com/jenkey2011/vuepress-deploy/issues/32? Is needed additional work to merge? Thanks!

**Pull request merged**
